In [33]:
pip install gmaps

Requirement already satisfied: gmaps in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (0.9.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (7.6.5)
Requirement already satisfied: geojson>=2.0.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipython>=5.3.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (7.29.0)
Requirement already satisfied: six in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (1.16.0)
Requirement already satisfied: traitlets>=4.3.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (5.1.0)
Requirement already satisfied: appnope in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: pickleshare in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: decorator in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (5.1.0)
Requirement already satisfied: jedi>=0.16 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.18.0)
Requirement already satisfied: pygments in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (2.10.0)
Requirement already satisfied: backcall in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (3.0.20)
Requirement already satisfied: pexpect>4.3 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: setuptools>=18.5 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (58.0.4)
Requirement already satisfied: matplotlib-inline in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: nbformat>=4.2.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.3)
Requirement already satisfied: ipython-genutils~=0.2.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (6.4.1)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.4.1)
Requirement already satisfied: jupyter-client<8.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.12)
Requirement already satisfied: tornado<7.0,>=4.2 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.8.2)
Requirement already satisfied: python-dateutil>=2.1 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.2)
Requirement already satisfied: pyzmq>=13 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (22.2.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (4.8.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (21.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: wcwidth in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.5)
Requirement already satisfied: Send2Trash>=1.5.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.8.0)
Requirement already satisfied: prometheus-client in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.11.0)
Requirement already satisfied: jinja2 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.3)
Requirement already satisfied: nbconvert in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.1.0)
Requirement already satisfied: argon2-cffi in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.1.0)
Requirement already satisfied: terminado>=0.8.3 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.9.4)
Requirement already satisfied: cffi>=1.0.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.14.6)
Requirement already satisfied: pycparser in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: jupyterlab-pygments in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: testpath in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.0)
Requirement already satisfied: bleach in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.0.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.3)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.3)
Requirement already satisfied: defusedxml in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: nest-asyncio in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: async-generator in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.10)

Requirement already satisfied: webencodings in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: packaging in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/ganghoonkim/opt/anaconda3/lib/python3.9/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

In [34]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [35]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Bengkulu,ID,2022-02-02 05:35:23,-3.8004,102.2655,79.03,71,100,3.40
1,1,Moron,AR,2022-02-02 05:35:24,-34.6534,-58.6198,74.98,74,2,5.55
2,2,Saldanha,ZA,2022-02-02 05:34:00,-33.0117,17.9442,64.45,92,89,13.06
3,3,Punta Arenas,CL,2022-02-02 05:35:24,-53.1500,-70.9167,44.71,70,75,14.97
4,4,Rikitea,PF,2022-02-02 05:35:25,-23.1203,-134.9692,78.30,68,95,5.10

In [36]:
# Get the data type
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [37]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [38]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [39]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [41]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [43]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Bengkulu,ID,2022-02-02 05:35:23,-3.8004,102.2655,79.03,71,100,3.40
4,4,Rikitea,PF,2022-02-02 05:35:25,-23.1203,-134.9692,78.30,68,95,5.10
8,8,Busselton,AU,2022-02-02 05:35:26,-33.6500,115.3333,86.04,30,25,7.67
14,14,Touros,BR,2022-02-02 05:35:22,-5.1989,-35.4608,76.10,81,64,8.08
17,17,Vanimo,PG,2022-02-02 05:35:30,-2.6741,141.3028,79.38,87,87,4.81
18,18,Hithadhoo,MV,2022-02-02 05:35:28,-0.6000,73.0833,82.78,70,8,9.31
20,20,Sibolga,ID,2022-02-02 05:35:31,1.7427,98.7792,83.57,68,92,4.03
23,23,Carnarvon,AU,2022-02-02 05:35:32,-24.8667,113.6333,84.27,70,99,16.11
24,24,Atuona,PF,2022-02-02 05:35:33,-9.8000,-139.0333,78.71,75,13,20.00
26,26,Vaini,TO,2022-02-02 05:35:34,-21.2000,-175.2000,84.36,74,20,6.91

In [44]:
preferred_cities_df.count()

City_ID       134
City          134
Country       134
Date          134
Lat           134
Lng           134
Max Temp      134
Humidity      134
Cloudiness    134
Wind Speed    134
dtype: int64

In [45]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

         City Country  Max Temp      Lat       Lng Hotel Name
0    Bengkulu      ID     79.03  -3.8004  102.2655
4     Rikitea      PF     78.30 -23.1203 -134.9692
8   Busselton      AU     86.04 -33.6500  115.3333
14     Touros      BR     76.10  -5.1989  -35.4608
17     Vanimo      PG     79.38  -2.6741  141.3028
18  Hithadhoo      MV     82.78  -0.6000   73.0833
20    Sibolga      ID     83.57   1.7427   98.7792
23  Carnarvon      AU     84.27 -24.8667  113.6333
24     Atuona      PF     78.71  -9.8000 -139.0333
26      Vaini      TO     84.36 -21.2000 -175.2000

In [46]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [48]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [49]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Bengkulu,ID,79.03,-3.8004,102.2655,Grage Hotel Bengkulu
4,Rikitea,PF,78.30,-23.1203,-134.9692,People ThankYou
8,Busselton,AU,86.04,-33.6500,115.3333,Observatory Guest House
14,Touros,BR,76.10,-5.1989,-35.4608,INN NEW HORIZON
17,Vanimo,PG,79.38,-2.6741,141.3028,Vahmoneh Lodge Vanimo
18,Hithadhoo,MV,82.78,-0.6000,73.0833,Scoop Guest House
20,Sibolga,ID,83.57,1.7427,98.7792,Hotel Syariah CN Darussalam
23,Carnarvon,AU,84.27,-24.8667,113.6333,Hospitality Carnarvon
24,Atuona,PF,78.71,-9.8000,-139.0333,Villa Enata
26,Vaini,TO,84.36,-21.2000,-175.2000,Keleti Beach Resort

In [51]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [53]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [54]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [55]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))